### ISSUE TITLE
✨ [New]: add Environment variables to the TestConfig

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.testing#411]
### Description

Would it be possible to add Environment-Variables as a source for configuration-settings to the TestConfig ?
We're running our integration and smoke tests like this from a pipeline:

```yaml
- task: AzureCLI@2
    displayName: 'Run Integration Tests'
    inputs:
      azureSubscription: ${{parameters.azureResourceManagerConnection}}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        dotnet test OurTestProject.csproj
    env:
      Database__DbConnectionString: $(Project.ConnectionString)
      Database__DbClientId: '$(Project.ClientId)'
      Database__RequestAccessToken: true
      Storage__StorageAccountUri: $(Project.StorageAccount)
```

### Solution

Something like this I guess ?

```csproj
TestConfig.Create(options => options.AddEnvironmentVariables);
```
